src/devsite-paths.json
Added the path-prefix for app-builder
=> feat : Added the path-prefix for app-builder

src/steps/stringify.ts
Adds hideBreadcrumbNav to metadata if it exists.
**Screenshots**
- hideBreadcrumbNav exists in .md file (https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/test/index.md?plain=1#L2):
- hideBreadcrumbNav doesn't exist in .md file (https://github.com/AdobeDocs/adp-devsite-github-actions-test/blob/main/src/pages/index.md?plain=1#L6):
=> Add hideBreadcrumbNav to metadata

src/devsite-paths.json
Ticket: https://jira.corp.adobe.com/browse/DEVSITE-1399
=> onboard acrobat-sign-developer-guide

src/steps/create-page-blocks.js
Added the block attributes to the respective block.
=> fix : added the attribute

src/steps/mdx-to-gridtables.ts
Added the attributes in a new row.
**After Add**
=> fix : added the attribute in new row

src/devsite-paths.json
Added path prefix for adobe-io-events
=> onboard : added path prefix for adobe-io-events

src/steps/mdx-to-gridtables.ts
=> fix: add attributes per row

src/steps/create-page-blocks.js, src/steps/mdx-to-gridtables.ts
Handled in a single way instead of using if/else, and removed this [commit](https://github.com/aemsites/devsite-runtime-connector/pull/17/files).
=> feat: pass attribute for each row

src/steps/mdx-to-gridtables.ts
Pass attribute values in connector as they appear in md files:
- <img width="1728" alt="Screenshot 2024-12-06 at 11 51 17 AM" src="https://github.com/user-attachments/assets/e46472e3-eb72-419c-8fb2-619961e9ec21">
- <img width="1727" alt="Screenshot 2024-12-06 at 11 52 07 AM" src="https://github.com/user-attachments/assets/19161a2a-e8c9-494b-aac4-e8b77020e4d8">
=> Get number and boolean attributes

src/devsite-paths.json
Added path prefix for app-builder-template-registry
=> feat: onboard app-builder-template-registry

src/devsite-paths.json
Onboard [g11n-translation-service](https://github.com/AdobeDocs/g11n-translation-service/blob/f4795ea3de01d5f416cc0c25431a456459e167ca/gatsby-config.js#L14)
=> onboard g11n-translation-service

src/steps/mdx-to-gridtables.ts, src/steps/rewrite-links.ts
=> feat : embed local videos

src/steps/rewrite-links.ts
=> fix : path issues

src/steps/remove-code-classes.ts
Fix typescript error reported on `npm run deploy`
=> fix typescript error

src/devsite-paths.json
=> feat: onboard runtime repo

src/steps/mdx-to-gridtables.ts
https://jira.corp.adobe.com/browse/DEVSITE-1438
Make connector output slot-x-repeat gridtables, where 
- slot = number of columns
- repeat = number of rows
+------------------------------------------------+
| Codeblock                                      |
+------------------------------------------------+
| ```                                            |
| data-slots=heading, code                       |
|                                                |
| ```                                            |
+------------------------------------------------+
| ```                                            |
| data-repeat=2                                  |
|                                                |
| ```                                            | …
=> Slot x Repeat GridTables

src/devsite-paths.json
Ticket: https://jira.corp.adobe.com/browse/DEVSITE-1528
Path prefix: https://github.com/AdobeDocs/adobe-connect-sdk/blob/main/src/pages/config.md?plain=1#L2
=> onboard adobe-connect-sdk

src/steps/mdx-to-gridtables.ts
Fixed horizontal wrapper issues on the connector
Actually, the issue occurs when we use <HorizontalLine /> in the MD file. It automatically treats the next element as a slot and wraps it as a child, which is not the correct behavior. So, we updated the code to fix this issue, and it should work fine now. I've attached the screenshot below.
=> fix : horizontal line issue

src/steps/stringify.ts
Adding title, description, and search keywords into the htmlwrap
=> update on adding frontmatter

src/index.ts
When a page errors, it should display a 500 error and the offending line of code:
To test:
- check out this branch
- run local dev mode with https://github.com/AdobeDocs/adp-devsite and https://github.com/AdobeDocs/adp-devsite-github-actions-test
- navigate to: http://localhost:3000/github-actions-test/test/code
=> feat: when pages error, it should display a 500 error and the line
